name: echoflow
channels:
  - defaults
dependencies:
  - aiobotocore=2.4.2=py310hecd8cb5_0
  - aiohttp=3.8.3=py310h6c40b1e_0
  - aioitertools=0.7.1=pyhd3eb1b0_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - appnope=0.1.2=py310hecd8cb5_1001
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-timeout=4.0.2=py310hecd8cb5_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - bokeh=2.4.3=py310hecd8cb5_0
  - brotlipy=0.7.0=py310hca72f7f_1002
  - bzip2=1.0.8=h1de35cc_0
  - ca-certificates=2023.05.30=hecd8cb5_0
  - cchardet=2.1.7=py310hcec6c5f_0
  - certifi=2023.7.22=py310hecd8cb5_0
  - cffi=1.15.1=py310h6c40b1e_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - comm=0.1.2=py310hecd8cb5_0
  - cryptography=41.0.2=py310h3b477ad_0
  - debugpy=1.6.7=py310hcec6c5f_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - executing=0.8.3=pyhd3eb1b0_0
  - freetype=2.12.1=hd8bbffd_0
  - frozenlist=1.3.3=py310h6c40b1e_0
  - fsspec=2023.3.0=py310hecd8cb5_0
  - giflib=5.2.1=h6c40b1e_3
  - idna=3.4=py310hecd8cb5_0
  - intel-openmp=2023.1.0=ha357a0b_43547
  - ipykernel=6.19.2=py310h20db666_0
  - ipython=8.12.0=py310hecd8cb5_0
  - jedi=0.18.1=py310hecd8cb5_1
  - jinja2=3.1.2=py310hecd8cb5_0
  - jmespath=0.10.0=pyhd3eb1b0_0
  - jpeg=9e=h6c40b1e_1
  - jupyter_client=8.1.0=py310hecd8cb5_0
  - jupyter_core=5.3.0=py310hecd8cb5_0
  - lcms2=2.12=hf1fd2bf_0
  - lerc=3.0=he9d5cce_0
  - libcxx=14.0.6=h9765a3e_0
  - libdeflate=1.17=hb664fd8_0
  - libffi=3.4.4=hecd8cb5_0
  - libpng=1.6.39=h6c40b1e_0
  - libsodium=1.0.18=h1de35cc_0
  - libtiff=4.5.0=hcec6c5f_2
  - libwebp=1.2.4=hf6ce154_1
  - libwebp-base=1.2.4=h6c40b1e_1
  - lz4-c=1.9.4=hcec6c5f_0
  - markupsafe=2.1.1=py310hca72f7f_0
  - matplotlib-inline=0.1.6=py310hecd8cb5_0
  - mkl=2023.1.0=h59209a4_43558
  - mkl-service=2.4.0=py310h6c40b1e_1
  - mkl_fft=1.3.6=py310h3ea8b11_1
  - mkl_random=1.2.2=py310h3ea8b11_1
  - multidict=6.0.2=py310hca72f7f_0
  - ncurses=6.4=hcec6c5f_0
  - nest-asyncio=1.5.6=py310hecd8cb5_0
  - numpy=1.25.0=py310h827a554_0
  - numpy-base=1.25.0=py310ha186be2_0
  - openssl=3.0.9=hca72f7f_0
  - packaging=23.0=py310hecd8cb5_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.4.0=py310hcec6c5f_0
  - pip=23.2.1=py310hecd8cb5_0
  - platformdirs=2.5.2=py310hecd8cb5_0
  - prompt-toolkit=3.0.36=py310hecd8cb5_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pydantic=1.10.8=py310h6c40b1e_0
  - pygments=2.15.1=py310hecd8cb5_1
  - pyopenssl=23.2.0=py310hecd8cb5_0
  - pysocks=1.7.1=py310hecd8cb5_0
  - python=3.10.12=h5ee71fb_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pyyaml=6.0=py310h6c40b1e_1
  - pyzmq=25.1.0=py310hcec6c5f_0
  - readline=8.2=hca72f7f_0
  - s3fs=2023.3.0=py310hecd8cb5_0
  - s3transfer=0.6.0=py310hecd8cb5_0
  - setuptools=68.0.0=py310hecd8cb5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.2=h6c40b1e_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tbb=2021.8.0=ha357a0b_0
  - tk=8.6.12=h5d9f67b_0
  - tornado=6.3.2=py310h6c40b1e_0
  - traitlets=5.7.1=py310hecd8cb5_0
  - typing-extensions=4.7.1=py310hecd8cb5_0
  - typing_extensions=4.7.1=py310hecd8cb5_0
  - urllib3=1.26.16=py310hecd8cb5_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.38.4=py310hecd8cb5_0
  - wrapt=1.14.1=py310hca72f7f_0
  - xz=5.4.2=h6c40b1e_0
  - yaml=0.2.5=haf1e3a3_0
  - yarl=1.8.1=py310hca72f7f_0
  - zeromq=4.3.4=h23ab428_0
  - zlib=1.2.13=h4dc903c_0
  - zstd=1.5.5=hc035e20_0
  - pip:
      - aiosqlite==0.19.0
      - alembic==1.11.1
      - anyio==3.7.1
      - apprise==1.4.5
      - asciitree==0.3.3
      - asgi-lifespan==2.1.0
      - asyncpg==0.28.0
      - attrs==23.1.0
      - azure-common==1.1.28
      - azure-core==1.29.2
      - azure-cosmos==4.5.0
      - azure-identity==1.14.0
      - azure-mgmt-containerinstance==10.1.0
      - azure-mgmt-core==1.4.0
      - azure-mgmt-resource==23.0.1
      - boto3==1.24.59
      - botocore==1.27.59
      - cachetools==5.3.1
      - cftime==1.6.2
      - click==8.1.6
      - cloudpickle==2.2.1
      - colorama==0.4.6
      - coolname==2.2.0
      - croniter==1.4.1
      - dask==2023.3.1
      - dateparser==1.1.8
      - distributed==2023.3.1
      - docker==6.1.3
      - echopype==0.7.2.dev40+g6671fec
      - entrypoints==0.4
      - exceptiongroup==1.1.2
      - fastapi==0.100.1
      - fasteners==0.18
      - geographiclib==2.0
      - geopy==2.3.0
      - google-auth==2.22.0
      - greenlet==2.0.2
      - griffe==0.32.3
      - h11==0.14.0
      - h2==4.1.0
      - hpack==4.0.0
      - httpcore==0.17.3
      - httpx==0.24.1
      - hyperframe==6.0.1
      - isodate==0.6.1
      - jsonpatch==1.33
      - jsonpointer==2.4
      - jsonschema==4.18.4
      - jsonschema-specifications==2023.7.1
      - kubernetes==27.2.0
      - locket==1.0.0
      - mako==1.2.4
      - markdown==3.4.4
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - more-itertools==8.13.0
      - msal==1.23.0
      - msal-extensions==1.0.0
      - msgpack==1.0.5
      - mypy-boto3-s3==1.28.19
      - mypy-boto3-secretsmanager==1.28.24
      - netcdf4==1.6.4
      - numcodecs==0.11.0
      - oauthlib==3.2.2
      - orjson==3.9.2
      - pandas==1.5.3
      - partd==1.4.0
      - pathspec==0.11.2
      - pendulum==2.1.2
      - portalocker==2.7.0
      - prefect==2.11.2
      - prefect-aws==0.3.6
      - prefect-azure==0.2.11
      - prefect-dask==0.2.4
      - psutil==5.9.5
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pyjwt==2.8.0
      - pynmea2==1.19.0
      - python-slugify==8.0.1
      - pytz==2023.3
      - pytzdata==2020.1
      - readchar==4.0.5
      - referencing==0.30.0
      - regex==2023.6.3
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rich==13.5.2
      - rpds-py==0.9.2
      - rsa==4.9
      - ruamel-yaml==0.17.32
      - ruamel-yaml-clib==0.2.7
      - scipy==1.11.1
      - sniffio==1.3.0
      - sortedcontainers==2.4.0
      - sqlalchemy==2.0.19
      - starlette==0.27.0
      - tblib==2.0.0
      - text-unidecode==1.3
      - toml==0.10.2
      - toolz==0.12.0
      - typer==0.9.0
      - tzdata==2023.3
      - tzlocal==5.0.1
      - uvicorn==0.23.2
      - watchtower==3.0.1
      - websocket-client==1.6.1
      - websockets==11.0.3
      - xarray==2023.7.0
      - xarray-datatree==0.0.6
      - zarr==2.16.0
      - zict==3.0.0
prefix: /Users/soham/anaconda3/envs/echoflow
